### PR TITLE
cake: Upgrade core libraries to 0.28.0

### PR DESCRIPTION
**Pull request by nalla**

### CODE REVIEW

**Comment by nalla** [comment]
@devlead I only changed `build.cake` to be compatible, so `dotnet-cake build.cake` works like a charme. The error in appveyor uses a broken `Cake.Recipe` I guess..

**Comment by gep13** [comment]
@nalla the latest version of Cake.Recipe, which Cake.Slack is using, now requires the use of Cake 0.28.0, so this:

https://github.com/cake-contrib/Cake.Slack/blob/master/tools/packages.config#L3

Would need to get changed.

**Comment by gep13** [comment]
@nalla fairly sure that this:

https://github.com/cake-contrib/Cake.Slack/blob/master/nuspec/nuget/Cake.Slack.nuspec#L18

Would need to change as well in order for this PR to work.

However, based on the guidance coming out of Microsoft just now, I have to admit that I am not convinced that this is the correct approach.

**Comment by nalla** [comment]
Looks good now. thanks @gep13 🙇

**Comment by nalla** [comment]
@gep13 what do you mean with guidance from microsoft?

**Comment by gep13** [comment]
@nalla I was referring to a recent series of tweets from Immo which states that .NET Standard 2 will not work in earlier versions of .NET Framework anymore, and as a result, if using .NET Standard 2 you will need to use 4.7.2.  This was mentioned here:

https://twitter.com/terrajobst/status/1031999730320986112

As a result, at the minute, we are thinking that it might be wise to leave the cross-compiling to multiple targets in play.  However, we haven't come to a decision on what the best recommendation is yet.

**Comment by nalla** [comment]
@gep13 @devlead I changed the PR to only update the Cake.Common version. I'll leave the decision about `netstandard` vs. `net46` up to you 😄

**Comment by gep13** [comment]
@vhatsura yes, that is correct.  Cake.Slack already does target this, so you should be good to go.

**Comment by gitfool** [comment]
Please update this to Cake 0.30.0 then merge and release. 😉

**Comment by gep13** [comment]
@nalla your changes have been merged, thanks for your contribution 👍

**Pull request merged**
